version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - db:/var/lib/mysql
      - ./docker-entrypoints/mysql/mysql_init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --local-infile=1
volumes:
  db:
    driver: local